CREATE TABLE TB_PHONE_NUMBER_TYPE(
PNT_CODIGO INT IDENTITY NOT NULL PRIMARY KEY, 
PNT_NAME VARCHAR(30) NOT NULL
)

CREATE TABLE TB_PERSON_PHONE(
 PEP_CODIGO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 PEP_PHONE_NUMBER VARCHAR(15) NOT NULL UNIQUE,
 PEP_PNTCODIGO INT NOT NULL, 
 CONSTRAINT FK_PEPPNTCODIGO FOREIGN KEY(PEP_PNTCODIGO) REFERENCES TB_PHONE_NUMBER_TYPE(PNT_CODIGO)

)


---inserts de teste
INSERT INTO TB_PHONE_NUMBER_TYPE
VALUES
('Local phone'),
('Cellphone')


INSERT INTO TB_PERSON_PHONE
VALUES 
('(19)99999-2883', 1),
('(19)99999-4021', 2)